services:
  web:
    build: .
    command: sleep infinity
    volumes:
      - .:/workspace:cached
    environment:
      EDITOR: "vi"
      BINDING: "0.0.0.0"
    working_dir: /workspace
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: "Azia/Tokyo"
    ports:
      - "3306:3306"
    restart: always

volumes:
  mysql_data:
